# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_updater.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogUpdater(object):
    def setupUi(self, DialogUpdater):
        DialogUpdater.setObjectName("DialogUpdater")
        DialogUpdater.resize(600, 400)
        DialogUpdater.setWindowTitle("GitHub HOST Updater")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogUpdater.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogUpdater)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(DialogUpdater)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)

        self.retranslateUi(DialogUpdater)
        QtCore.QMetaObject.connectSlotsByName(DialogUpdater)

    def retranslateUi(self, DialogUpdater):
        pass
import res_rc
