# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogUpdate(object):
    def setupUi(self, DialogUpdate):
        DialogUpdate.setObjectName("DialogUpdate")
        DialogUpdate.resize(600, 100)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogUpdate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(DialogUpdate)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.progressBar = QtWidgets.QProgressBar(DialogUpdate)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.labelItem = QtWidgets.QLabel(DialogUpdate)
        self.labelItem.setText("")
        self.labelItem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelItem.setObjectName("labelItem")
        self.verticalLayout.addWidget(self.labelItem)

        self.retranslateUi(DialogUpdate)
        QtCore.QMetaObject.connectSlotsByName(DialogUpdate)

    def retranslateUi(self, DialogUpdate):
        _translate = QtCore.QCoreApplication.translate
        self.labelTitle.setText(_translate("DialogUpdate", "Progress"))
